site_name: InCtrl
theme:
  name: material
  features:
    - navigation.sections

# Markdown extensions
markdown_extensions:
  - attr_list
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - "Introduction": "index.md"
  - "Supported instruments": "supported_instruments.md"
  - "Name and params resolution": "name_resolution.md"
  - "Oscilloscope API": "oscilloscope.md"
  - "Waveform": "waveform.md"
  - "Duration": "duration.md"
